name: Display Message on Push and Pull Request

# Trigger the workflow for push and pull_request events
on:
  push:
    branches:
      - main  # or any branch you want to target
  pull_request:
    branches:
      - main  # or any branch you want to target

jobs:
  display-message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display message on push
        if: github.event_name == 'push'
        run: echo "A push event has occurred. Changes have been pushed to the repository!"

      - name: Display message on pull request
        if: github.event_name == 'pull_request'
        run: echo "A pull request has been created or updated. Review and merge as needed."

